name: "build"
on:
  push: 
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.81
          target: aarch64-apple-ios

      - name: Install deps
        run: |
          brew install ninja gcc
      - name: build
        run: |
          cargo build --target aarch64-apple-ios